# Generated by Django 3.1.6 on 2021-02-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the problem statement', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='problems/images')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='problems/images')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='problems/images')),
                ('problem_description', models.TextField()),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('Em', 'Extreme')], default='M', max_length=50)),
                ('points_worth', models.PositiveIntegerField(default=5)),
                ('category', models.CharField(choices=[('P', 'Programming'), ('D', 'Electrical Circuit Design'), ('W', 'Web Development'), ('S', 'Electrical Systems Design')], default='P', max_length=50)),
                ('file_one', models.FileField(blank=True, null=True, upload_to='problems/files')),
                ('file_two', models.FileField(blank=True, null=True, upload_to='problems/files')),
                ('file_three', models.FileField(blank=True, null=True, upload_to='problems/files')),
            ],
        ),
    ]
