# Generated by Django 3.1.6 on 2021-02-19 06:08

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
