# Generated by Django 3.1.6 on 2021-02-14 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(help_text='Enter a short description of the solution', max_length=300)),
                ('description_of_answer', models.TextField(blank=True, help_text='Add a text explanation of the problem if there is any', null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='problems/images')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='problems/images')),
                ('image_three', models.ImageField(blank=True, null=True, upload_to='problems/images')),
                ('file_one', models.FileField(blank=True, null=True, upload_to='solutions/files')),
                ('file_two', models.FileField(blank=True, null=True, upload_to='solutions/files')),
                ('file_three', models.FileField(blank=True, null=True, upload_to='solutions/files')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RecommendedSolution',
            fields=[
                ('solution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solutions.solution')),
                ('link_to_video', models.URLField(help_text='Enter link to video posted on youtube, or any video hosting platform')),
            ],
            bases=('solutions.solution',),
        ),
        migrations.CreateModel(
            name='StudentSolution',
            fields=[
                ('solution_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solutions.solution')),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
            ],
            bases=('solutions.solution',),
        ),
    ]
