# Generated by Django 3.1.6 on 2021-02-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedsolution',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_solution', to='problems.problem'),
        ),
    ]
