# Generated by Django 3.1.6 on 2021-02-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20210219_0608'),
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedsolution',
            name='problem',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recommended_solution', to='problems.problem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsolution',
            name='problem',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='student_solutions', to='problems.problem'),
            preserve_default=False,
        ),
    ]
