# Generated by Django 3.1.6 on 2021-02-19 06:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_auto_20210219_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=' ', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
